services:
  ts-proxy:
    build: .
    image: registry.gitlab.com/kpihx-labs/proxies/ts-proxy:latest
    volumes:
      - .:/app
      - ~/.ts-proxy:/root/.ts-proxy
      - /var/run/secrets/ts-auth.json:/var/run/secrets/ts-auth.json:ro
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: host
